import Head from "next/head";
import Card from "../src/components/Card";
import Navbar from "../src/components/Navbar";
import SubHeader from "../src/components/SubHeader";
import axios from "axios";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import {
  setActiveRides,
  selectActiveRides,
} from "../features/activeRidesSlice";

export default function Home({ data }) {
  const dispatch = useDispatch();

  const activeRides = useSelector(selectActiveRides);

  useEffect(() => {
    calculateDistance();
    dispatch(setActiveRides({ activeRides: data.rides }));
  }, [data.rides]);

  const calculateDistance = () => {
    let distance = 0;

    data?.rides.forEach((ride) => {
      for (let i = 0; i < ride.station_path.length; i++) {
        let difference = ride.station_path[i] - data.user.station_code;

        if (difference < distance) distance = difference;
      }
      distance = Math.abs(distance);
      ride.distance = distance;
    });
  };

  return (
    <div className="bg-gray-800 h-screen">
      <Head>
        <title>Edvora Rides</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Navigation*/}
      <Navbar user={data.user} />

      <div className="bg-gray-800">
        {/*SubHeader Section*/}
        <SubHeader rides={data.rides} />

        {/*Cards Section*/}
        {activeRides.length > 0 ? (
          activeRides.map(
            ({
              id,
              origin_station_code,
              station_path,
              date,
              map_url,
              state,
              city,
              distance,
            }) => (
              <Card
                key={id}
                id={id}
                stationCode={origin_station_code}
                stationPath={station_path}
                date={date}
                map={map_url}
                state={state}
                city={city}
                distance={distance}
              />
            )
          )
        ) : (
          <div className="w-full text-white text-center my-12">
            No rides available
          </div>
        )}
      </div>
    </div>
  );
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const rides = await axios
    .get("https://assessment.api.vweb.app/rides")
    .then((response) => {
      return response.data;
    })
    .catch((error) => {
      if (error) {
        return error;
      }
    });

  const user = await axios
    .get("https://assessment.api.vweb.app/user")
    .then((response) => {
      return response.data;
    })
    .catch((error) => {
      if (error) {
        return error;
      }
    });

  const data = {
    user: user,
    rides: rides,
  };

  return {
    props: {
      data,
    },
  };
}
